name: Release

on:
  push:
    tags:
      - v*

env:
  DEFAULT_PYTHON: '3.13'

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    if: github.repository == 'dolfinus/setuptools-git-versioning'  # prevent running on forks

    environment:
      name: pypi
      url: https://pypi.org/p/onetl
    permissions:
      id-token: write # to auth in PyPI
      contents: write # to create Github release

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-release-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-release-${{ hashFiles('requirements*.txt') }}
            ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-release-
            ${{ runner.os }}-python
            ${{ runner.os }}-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-doc.txt

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Patch setup.py with explicit version number
      # Fix for https://github.com/dolfinus/setuptools-git-versioning/issues/72#issuecomment-1312589464
        run: |
          version=$(echo $GITHUB_REF_SLUG | sed -E "s/v(.*)/\1/")
          sed -i -E "/from setuptools_git_versioning.*/d" setup.py
          sed -i -E "s/version=.*/version='${version}',/" setup.py

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Build release notes
        run: |
          mkdir reports/
          pip install -e .
          version=$(echo $GITHUB_REF_SLUG | sed -E "s/v(.*)/\1/")
          # lines 1 and 3 are empty, line 2 contains version number, line 4 contains release date
          changelog generate-md -c ./docs/conf.py CHANGELOG.rst -v $version | sed "1,4d" > reports/release.md
          sed -i -E 's/:github-user:`(.*)`/@\1/g' reports/release.md
          sed -i -E 's/:issue:`(.*)`/#\1/g' reports/release.md
          sed -i -E 's/:pr:`(.*)`/#\1/g' reports/release.md

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          body_path: reports/release.md
          files: |
            dist/*
